version: '3.5'

services:
  node:
    build: ./
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=postgres_db
      - POSTGRES_DB=motora
      - POSTGRES_PORT=5432

    depends_on: 
      - dbase
    ports:
      - "5000:5000"
  dbase:
    container_name: postgres_db
    restart: always
    ports: 
      - '5431:5432'
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=motora
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    image: postgres:14.9-alpine
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=000999
    ports:
      - "16543:80"
    depends_on:
      - dbase